In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [1]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
print(stopwords.words('english'))

In [9]:
import pandas as pd
df = pd.read_csv("fake.csv")
dt = pd.read_csv("true.csv")
print(df.head())
print(dt.head())

/tmp/ipykernel_6582/144402508.py:2: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("fake.csv")

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  December 31, 2017        NaN        NaN        NaN        NaN        NaN
1  December 31, 2017        NaN        NaN        NaN        NaN        NaN
2  December 30, 2017        NaN        NaN        NaN        NaN        NaN
3  December 29, 2017        NaN        NaN        NaN        NaN        NaN
4  December 25, 2017        NaN        NaN        NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 162 Unnamed: 163 Unnamed: 164 Unnamed: 165  \
0        NaN  ...          NaN          NaN          NaN          NaN
1        NaN  ...          NaN          NaN          NaN          NaN
2        NaN  ...          NaN          NaN          NaN          NaN
3        NaN  ...          NaN          NaN          NaN          NaN
4        NaN  ...          NaN          NaN          NaN          NaN

  Unnamed: 166 Unnamed: 167 Unnamed: 168 Unnamed: 169 Unnamed: 170  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

  Unnamed: 171
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

[5 rows x 172 columns]
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date
0  December 31, 2017
1  December 29, 2017
2  December 31, 2017
3  December 30, 2017
4  December 29, 2017

In [14]:
dt['Label']=0
df['Label']=1

In [11]:
new_dataset=pd.concat([dt , df] , ignore_index = True)
new_dataset.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
new_dataset['content']=new_dataset.title +" " + new_dataset.text

In [23]:
new_dataset = new_dataset[['content','Label']]
new_dataset.head()

                                             content  Label
0  As U.S. budget fight looms, Republicans flip t...    NaN
1  U.S. military to accept transgender recruits o...    NaN
2  Senior U.S. Republican senator: 'Let Mr. Muell...    NaN
3  FBI Russia probe helped by Australian diplomat...    NaN
4  Trump wants Postal Service to charge 'much mor...    NaN

In [15]:
new_dataset = new_dataset[['content','Label']]
new_dataset.head()

                                             content  Label
0  As U.S. budget fight looms, Republicans flip t...    NaN
1  U.S. military to accept transgender recruits o...    NaN
2  Senior U.S. Republican senator: 'Let Mr. Muell...    NaN
3  FBI Russia probe helped by Australian diplomat...    NaN
4  Trump wants Postal Service to charge 'much mor...    NaN

In [21]:
port_stem = PorterStemmer()
stopwords = set(stopwords.words('english'))

NameError: name 'PorterStemmer' is not defined

In [16]:
import re
def stemming(content):
  content = re.sub('[^a-zA-Z]',' ',content).lower().split()
  content = [port_stem.stem(word) for word in content if not word in stopwords]
  content = ' '.join(content)
  return content

In [18]:
from tqdm import tqdm
tqdm.pandas()

In [19]:

new_dataset['content'] = new_dataset['content'].progress_apply(stemming)

  0%|          | 1/44919 [00:00<00:31, 1440.85it/s]

NameError: name 're' is not defined

In [24]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
port_stem = PorterStemmer()
stopwords = set(stopwords.words('english'))